# arxivの学問領域の指定
subject: 'cat:astro-ph.CO OR cat:astro-ph.EP OR cat:astro-ph.GA OR cat:nlin.*'

# 検索キーワード
keywords:
        molecular: 1
        instability: 1
        protostar: 2
        protoplanetary: 2
        star-forming: 1
        MHD: 1
        accretion: 1
        outflow: 2
        CO: 1
        ALMA: 1
        Ophiuchus: 3
        simulation: 2
        
# 通知の閾値
score_threshold: 3
