# arxivの学問領域の指定
subject: 'cat:astro-ph.CO OR cat:astro-ph.EP OR cat:astro-ph.GA OR cat:nlin.*'

# 検索キーワード
keywords:
        molecular: 3
        instability: 1
        detected: 2
        dynamics: 2
        turbulent: 1
        observation: 2
# 通知の閾値
score_threshold: 0
