# arxivの学問領域の指定
subject: 'cat:astro-ph.CO OR cat:astro-ph.EP OR cat:astro-ph.GA OR cat:nlin.*'

# 検索キーワード
keywords:
        molecular: 1
        instability: 1
        detected: 1
        dynamics: 1
        turbulent: 1
        observations: 1
        formation: 1
        simulations: 1
        chemistry: 1
        spectra: 1
# 通知の閾値
score_threshold: 2
